name: eda-streamlit-fastapi
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.13
  - pip
  - ipykernel
  - pip:
      - streamlit
      - pandas
      - numpy
      - matplotlib
      - seaborn
      - scikit-learn
      - fastapi
      - optuna
      - uvicorn
      - xgboost
      - joblib
      - pyyaml
      - -e .
